# Generated by Django 2.2 on 2019-03-01 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(default='', max_length=50)),
                ('school', models.IntegerField(default=2019)),
                ('subject', models.IntegerField(default=20)),
                ('hours', models.IntegerField(default=20)),
                ('date_of_work', models.DateField(default=20)),
                ('date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
