# Generated by Django 2.2 on 2019-03-01 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mini_projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecardmodel',
            old_name='Teacher_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='timecardmodel',
            name='date_of_entry',
        ),
        migrations.RemoveField(
            model_name='timecardmodel',
            name='date_of_work',
        ),
        migrations.AddField(
            model_name='timecardmodel',
            name='dow',
            field=models.DateField(default=datetime.date(2019, 3, 1)),
        ),
        migrations.AddField(
            model_name='timecardmodel',
            name='entryDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 17, 54, 44, 918609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timecardmodel',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='timecardmodel',
            name='school',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='timecardmodel',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
